include = ["AGENTS.md"]
exclude = []

[[presets]]
name = "src"
include = ["**/*.c", "**/*.h"]
exclude = []

[[presets]]
name = "csrc"
include = ["**/*.c", "**/*.h", "**/CMakeLists.txt"]
exclude = []

[[presets]]
name = "cm"
include = ["**/CMakeLists.txt"]
